### PR TITLE
Add request object to authorize call

### PR DESCRIPTION
**Pull request by arcticShadow**
* request object passed to authorize
* block callback adds heeader to request
* request object returned from authorize call

Issue: #30
Approver: Pull Request

### CODE REVIEW

**Comment by arcticShadow** [comment]
I've fixed some of the existing tests - that broke when I implemented this (due to global fetch being called with different args) 

I have not yet added any tests for this - as i'm not 100% on the implementation - looking for some feedback. 

I've kept the authentication contract the same, but added functionality, in a backward compatible way. If you're open to the contract for 'authenticate' changing, then this would be a much cleaner addition. (i.e. instead of `authenticate` implementors calling the `block` callback one of many times, they directly interact with the `Request` object as required, returning it when they are done.)

**Comment by jerelmiller** [comment]
Oh gosh, I stepped away from a lot during the holidays, and never did revisit this PR. I am so very sorry.

I'd like to better understand what kind of problems this solves. Right now, the `fetch` action exported from this library is a thin layer on top of the real `fetch` API, so you would normally have all access to set any `fetch` options as you normally would. (i.e. `fetch('/url', { credentials: 'same-origin' })` should still work the same). The authorizer is more a way to set header information using data from the `session` state.

That being said, I know this may be a pretty naive implementation at this point. What other kinds of `fetch` options would benefit from data in the session?

**Comment by arcticShadow** [comment]
No worries on the delay. I'm actually not working on the project i did this up for - nor at the company either. 

The intention behind this was to enable more than just header based auth to be injected by the system. 

Yes, I could work with the fetch object directly on an as nbeeded basis, but this requires that each caller of fetch knows an understands the  authentication mechanisims of the system (which is why I looked to use this module in the first place, as my callers did not know the auth requirements. 

I think for this moving forwards, @muntact should get involved, as Hes taken over where I left off (I'm not even sure if this method is still valid for where the project has gone)

**Comment by jerelmiller** [comment]
I'm going to close this for now. Thanks a bunch for submitting this. I'm going to wait a little bit longer to see if there is a real need for this. If that does happen, I'd definitely love to revisit this.

**Comment by colmbrady** [comment]
Hey @jerelmiller - Id be interested in reopening this contrib.

I need a way of templating which options go into fetch depending on what authenticator is in use. For example, if using cookie based auth, then we would want to send the cookie each time on fetch using credentials: same-origin

We have a component based app, and each component is not aware of how the parent app authenticated (could be oauth implicit/cookie or other), so ideally it could just call "fetch" and not know the details of the auth and how to pass the auth data. So if we had a mechanism to template extra options into this libraries fetch wrapper depending on the auth strategy (globally), then this would fit in nicely with our architecture.

What you think?

**Comment by jerelmiller** [comment]
Hey @colmbrady!

Apologies, I've been on vacation the last couple weeks and haven't really been watching notifications.

To ensure I'm understanding you correctly, are you looking for the ability to define additional request options in the authorizer itself based on the authenticator that is currently in use?

For example, for the cookie auth like you mention above, I'm assuming you'd want to ability to do something like this correct? (not likely the final API, but just for demonstration)

```js
const authorizer = (data, setHeader, authenticator) => {
  if (authenticator === 'cookie') {
    setHeader('credentials', 'same-origin')
  }

  if (authenticator === 'token') {
    setHeader('Authorization', `Bearer ${data.token}`)
  }
}
```

Does this sound like I'm on the right track to understanding this? If so, could you give me an idea of what kind of properties you are looking to add to the request? Are they all request headers or would you need to be able to set more on the request as well?

Thanks for using the library and apologies for taking so long to reply.

**Comment by colmbrady** [comment]
Hi @jerelmiller.

No worries on the length of time on response, Im also multi tasking so its not a problem.

I think we talking about the same thing.

Firstly, just to be clear about what I believe we are talking about!

authenticator: I understand this to be the component that can negotiate auth with the server.
authorizer: I understand this to be a pluggable thing used to attach credentials to subsequent interactions with server. e.g. `fetch`. 

So given those definitions, my requirements would be something like this:

- app developers can create instances of `authenticators`. (e.g. OAuth Grant, cookie, OAuth Implicit etc).
- app developers use the `authenticators` in their apps (myauth.authenticate(...))
- developers subsequently use `fetch` to call APIs. however they should not have to handle the specifics of how to construct an authenticated fetch call. This is done by the authorizer that is associated with the in-use authenticator. Developers construct URLs to call and can still use Fetch as intended, but they dont worry about auth details.

So for a cookie use  case, the `authorizer` would have to pass {credentials: 'same-origin'} as a fetch **option** (not a header) to ensure cookies get sent to the server.

And for Oauth, the Bearer token is attached as a header. (Which is the already implemeted the case I believe).

Again, just to re-iterate, the reason for abstracting the auth details from the app developers using `Fetch` is because of our component based architecture, where components DONT know how the auth was done so cant really reference auth details.

Hope this makes sense.

**Comment by colmbrady** [comment]
So more specifically, I think I could achieve what I want if we had a way of merging in fetch options into any fetch calls been made via the fetch dispatcher.

**Comment by colmbrady** [comment]
@jerelmiller is this still on your radar? If not - Id be open to contributing a P.R with some guidance.

**Pull request closed without merging**
